#!/usr/bin/awk -f
# When receiving output from du, outputs files larger than 1 GiB in red
# and files larger than 0.5 GiB in yellow. Others are not outputted.
{
	if ($1 > 1048576) {size=$1;$1=""; printf "\033[1;31m%3.4f GiB\t\t%s\033[0;0m\n",size/1048576,$0 } # > 1GB
	else if ($1 > 524288) {size=$1;$1=""; printf "\033[1;33m%3.4f GiB\t\t%s\033[0;0m\n",size/1048576,$0 } # > 0.5GB
}
